version: '2'
services:
  comicdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - comicdb

  comicdb-postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=comicDB"
    networks:
      - comicdb

networks:
  comicdb:
    driver: bridge
