version: '2'

services:
  comicdb:
    container_name: comicdb
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres:postgres
    volumes:
      - .:/opt/ComicDB
    working_dir: /opt/ComicDB
    ports:
      - "3000:3000"
    networks:
      - comicdb

  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=comicDB"
      - "POSTGRES_USER=ComicDB"
    networks:
      - comicdb

networks:
  comicdb:
    driver: bridge
